---

- hosts: all
  become: true
  tasks:

  - name: install tmux and mc and update cache
    package:
      name: 
        - "{{ tmux_package }}"
        - "{{  mc_package }}"
      state: latest
      update_cache: yes

