---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install tmux
    apt:
      name: tmux
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install mc
    apt:
      name: mc
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
