---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install tmux 
    apt:
      name: tmux
      state: latest
    when: ansible_distribution == "Debian"

  - name: install mc
    apt:
      name: mc
      state: latest
    when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  tasks:

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- hosts: pve_servers
  become: true
  tasks:

  - name: install proxmox
    apt:
      name: proxmox
      state: latest

