---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: all
  become: true
  tasks:

  - name: install tmux 
    apt:
      name: tmux
      state: latest
    when: ansible_distribution == "Debian"

  - name: install mc
    apt:
      name: mc
      state: latest
    when: ansible_distribution == "Debian"


- hosts: pve_servers
  become: true
  tasks:

  - name: install proxmox
    apt:
      name: proxmox
      state: latest

