- name: install web server packages
  tags: apache,apache2,centos,httpd,debian
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable service
  tags: apache,apache2,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: restart httpd
  tags: apache,httpd
  service:
    name: "{{ apache_service}}"
    state: restarted
  when: apache.changed

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
